// This would typically come from a CMS or database

export type Project = {
  title: string
  location: string
  year: string
  type: string
  description: string
  highlights: string[]
  heroImage: string
  heroVideo?: string
  gallery: string[]
}

export const projectData: Record<string, Project> = {
  'munas-residence': {
    title: 'Munas Residence',
    location: 'Trikaripur, Kasargod',
    year: '2025',
    type: 'Residential',
    description: 'A beautiful residential project crafted for Munas in Trikaripur, Kasargod, offering contemporary design and comfortable living spaces.',
    highlights: [
      'Client: Munas',
      'Location: Trikaripur, Kasargod',
      'Residential project',
      'Contemporary design',
    ],
    heroImage: '/images/projects/munas/1.jpg',
    gallery: [
      '/images/projects/munas/1.jpg',
      '/images/projects/munas/2.jpg',
      '/images/projects/munas/3.jpg',
      '/images/projects/munas/4.jpg',
      '/images/projects/munas/5.jpg',
      '/images/projects/munas/6.jpg',
      '/images/projects/munas/7.jpg',
      '/images/projects/munas/8.jpg',
      '/images/projects/munas/9.jpg',
      '/images/projects/munas/10.jpg',
      '/images/projects/munas/11.jpg',
      '/images/projects/munas/12.jpg',
    ],
  },
  'nizar-residence': {
    title: 'Nizar Residence',
    location: 'Payyannur',
    year: '2025',
    type: 'Residential',
    description: 'A modern residential project designed for Mr. Nizar in Payyannur. This home features contemporary aesthetics combined with functional living spaces, optimized for comfort and style.',
    highlights: [
      'Client: Nizar',
      'Location: Payyannur',
      'Year: 2025',
      'Residential project',
      'Modern architectural design',
    ],
    heroImage: '/images/projects/nizar-residence/1.jpg',
    gallery: [
      '/images/projects/nizar-residence/1.jpg',
      '/images/projects/nizar-residence/2.jpg',
      '/images/projects/nizar-residence/3.jpg',
      '/images/projects/nizar-residence/4.jpg',
      '/images/projects/nizar-residence/5.jpg',
      '/images/projects/nizar-residence/6.jpg',
    ],
  },
  'marzook-residence': {
    title: 'Marzook Residence',
    location: 'Kunhimangalam',
    year: '2024',
    type: 'Residential',
    description: 'A contemporary residence crafted for Marzook in Kunhimangalam, featuring warm finishes, abundant daylight, and a seamless connection between indoor living and landscaped outdoor areas.',
    highlights: [
      'Client: Marzook',
      'Location: Kunhimangalam',
      'Year: 2024',
      'Residential project',
      'Indoor-outdoor flow with natural light',
    ],
    heroImage: '/images/projects/marzook/0.png',
    heroVideo: '/videos/projects/marzook/hero.mp4',
    gallery: [
      '/images/projects/marzook/0.png',
      '/images/projects/marzook/1.png',
      '/images/projects/marzook/2.png',
      '/images/projects/marzook/3.png',
    ],
  },
  'edathavalam': {
    title: 'Edathavalam',
    location: 'Trikaripur, Kasargod',
    year: '2024',
    type: 'Residential',
    description: 'Designed for Mr. Nizam, "Edathavalam" represents a harmonious blend of traditional architecture and modern living. Located in Trikaripur, Kasargod, this residence features open courtyards, abundant indoor greenery, and a warm, inviting atmosphere created through thoughtful lighting and material selection.',
    highlights: [
      'Client: Mr. Nizam',
      'Traditional Kerala elements',
      'Central courtyard with greenery',
      'Warm ambient lighting',
      'Indoor-outdoor living connection',
      'Sustainable design approach',
    ],
    heroImage: '/images/projects/edathavalam/1.jpg',
    gallery: [
      '/images/projects/edathavalam/1.jpg',
      '/images/projects/edathavalam/2.jpg',
      '/images/projects/edathavalam/3.jpg',
      '/images/projects/edathavalam/4.jpg',
      '/images/projects/edathavalam/5.jpg',
      '/images/projects/edathavalam/6.jpg',
      '/images/projects/edathavalam/7.jpg',
      '/images/projects/edathavalam/8.jpg',
      '/images/projects/edathavalam/9.jpg',
      '/images/projects/edathavalam/10.jpg',
      '/images/projects/edathavalam/11.jpg',
      '/images/projects/edathavalam/12.jpg',
      '/images/projects/edathavalam/13.jpg',
      '/images/projects/edathavalam/14.jpg',
      '/images/projects/edathavalam/15.jpg',
      '/images/projects/edathavalam/16.jpg',
      '/images/projects/edathavalam/17.jpg',
    ],
  },
  'shafeer-vellur': {
    title: 'Shafeer Residence',
    location: 'Vellur',
    year: '2022',
    type: 'Residential',
    description: 'A warm, wood-detailed family home crafted for Shafeer in Vellur. The interiors balance an airy layout with custom joinery, layered lighting, and a soft neutral palette. Open living, dining, and kitchen zones connect seamlessly, while built-ins and screens in rich timber add both storage and character.',
    highlights: [
      'Client: Shafeer',
      'Completed: 2022',
      'Location: Vellur',
      'Open-plan living, dining, and breakfast counter',
      'Warm timber staircase, screens, and built-ins',
      'Neutral palette with soft layered lighting',
    ],
    heroImage: '/images/projects/shafeer-vellur/4.jpg',
    gallery: [
      // '/images/projects/shafeer-vellur/1.jpg',
      '/images/projects/shafeer-vellur/2.jpg',
      '/images/projects/shafeer-vellur/3.jpg',
      '/images/projects/shafeer-vellur/4.jpg',
      '/images/projects/shafeer-vellur/5.jpg',
      '/images/projects/shafeer-vellur/6.jpg',
      '/images/projects/shafeer-vellur/7.jpg',
      '/images/projects/shafeer-vellur/8.jpg',
      '/images/projects/shafeer-vellur/9.jpg',
      '/images/projects/shafeer-vellur/10.jpg',
      '/images/projects/shafeer-vellur/11.jpg',
      '/images/projects/shafeer-vellur/12.jpg',
      '/images/projects/shafeer-vellur/13.jpg',
      '/images/projects/shafeer-vellur/14.jpg',
      '/images/projects/shafeer-vellur/15.jpg',
      '/images/projects/shafeer-vellur/16.jpg',
      '/images/projects/shafeer-vellur/17.jpg',
      '/images/projects/shafeer-vellur/18.jpg',
      '/images/projects/shafeer-vellur/19.jpg',
      '/images/projects/shafeer-vellur/20.jpg',
      '/images/projects/shafeer-vellur/21.jpg',
      '/images/projects/shafeer-vellur/22.jpg',
      '/images/projects/shafeer-vellur/23.jpg',
      '/images/projects/shafeer-vellur/24.jpg',
      '/images/projects/shafeer-vellur/25.jpg',
    ],
  },
  'luxury-residential-complex': {
    title: 'Luxury Residential Complex',
    location: 'Mumbai, India',
    year: '2024',
    type: 'Residential',
    description: 'A premium residential complex featuring compact yet luxurious apartments designed for modern urban living. The project emphasizes sustainable materials and energy-efficient design while maximizing space efficiency.',
    highlights: [
      'Sustainable building materials',
      'Energy-efficient design',
      'Compact luxury living',
      'Modern architectural aesthetics',
      'Green spaces integration',
    ],
    heroImage: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1920&h=1080&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop',
    ],
  },
  'modern-office-space': {
    title: 'Modern Office Space',
    location: 'Delhi, India',
    year: '2023',
    type: 'Commercial',
    description: 'A contemporary office space designed to foster collaboration and productivity. The design features flexible workspaces, natural lighting, and sustainable interior solutions.',
    highlights: [
      'Flexible workspace design',
      'Natural lighting optimization',
      'Sustainable materials',
      'Collaborative zones',
      'Modern aesthetics',
    ],
    heroImage: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1920&h=1080&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1497366412874-3415097a27e7?w=800&h=600&fit=crop',
    ],
  },
  'sustainable-living-hub': {
    title: 'Sustainable Living Hub',
    location: 'Bangalore, India',
    year: '2024',
    type: 'Mixed Use',
    description: 'An innovative mixed-use development combining residential, commercial, and community spaces with a strong focus on sustainability and environmental responsibility.',
    highlights: [
      'Mixed-use development',
      'Solar energy integration',
      'Water conservation systems',
      'Community spaces',
      'Eco-friendly materials',
    ],
    heroImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1920&h=1080&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop',
    ],
  },
  'boutique-hotel-design': {
    title: 'Boutique Hotel Design',
    location: 'Goa, India',
    year: '2023',
    type: 'Hospitality',
    description: 'A luxury boutique hotel featuring unique design elements that reflect local culture while maintaining modern comfort and elegance.',
    highlights: [
      'Cultural design integration',
      'Luxury interiors',
      'Sustainable hospitality design',
      'Unique architectural elements',
      'Premium guest experience',
    ],
    heroImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1920&h=1080&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1566073771219-8e0a3a4a3e3e?w=800&h=600&fit=crop',
    ],
  },
  'contemporary-villa': {
    title: 'Contemporary Villa',
    location: 'Pune, India',
    year: '2024',
    type: 'Residential',
    description: 'A stunning contemporary villa that seamlessly blends indoor and outdoor living spaces, featuring minimalist design and premium finishes.',
    highlights: [
      'Indoor-outdoor integration',
      'Minimalist design',
      'Premium finishes',
      'Modern architecture',
      'Landscape integration',
    ],
    heroImage: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1920&h=1080&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop',
    ],
  },
  // Add more projects as needed
  'urban-loft-renovation': {
    title: 'Urban Loft Renovation',
    location: 'Hyderabad, India',
    year: '2023',
    type: 'Residential',
    description: 'A complete renovation of an urban loft, transforming it into a modern, functional living space with industrial elements.',
    highlights: [
      'Industrial design elements',
      'Space maximization',
      'Modern renovation',
      'Functional layout',
      'Urban aesthetic',
    ],
    heroImage: 'https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=1920&h=1080&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop',
    ],
  },
  'corporate-headquarters': {
    title: 'Corporate Headquarters',
    location: 'Chennai, India',
    year: '2024',
    type: 'Commercial',
    description: 'A state-of-the-art corporate headquarters designed to reflect the company\'s values and provide an inspiring work environment.',
    highlights: [
      'Corporate identity design',
      'Modern workspace',
      'Premium finishes',
      'Technology integration',
      'Employee wellness focus',
    ],
    heroImage: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1920&h=1080&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop',
    ],
  },
  'eco-friendly-resort': {
    title: 'Eco-Friendly Resort',
    location: 'Kerala, India',
    year: '2023',
    type: 'Hospitality',
    description: 'An eco-friendly resort that harmonizes with its natural surroundings while providing luxury accommodations and sustainable amenities.',
    highlights: [
      'Eco-friendly design',
      'Natural integration',
      'Sustainable amenities',
      'Luxury accommodations',
      'Environmental consciousness',
    ],
    heroImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1920&h=1080&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop',
    ],
  },
  'minimalist-apartment': {
    title: 'Minimalist Apartment',
    location: 'Mumbai, India',
    year: '2024',
    type: 'Residential',
    description: 'A compact apartment redesigned with minimalist principles, maximizing space and functionality while maintaining elegance.',
    highlights: [
      'Minimalist design',
      'Space optimization',
      'Clean aesthetics',
      'Functional layout',
      'Premium materials',
    ],
    heroImage: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1920&h=1080&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop',
    ],
  },
  '3d-elevation-designs': {
    title: '3D Exterior Designs',
    location: '',
    year: '',
    type: '3D',
    description: 'Explore our comprehensive portfolio of high-quality 3D architectural facade renders, elevations, and exterior visualizations designed to preview beautiful custom homes.',
    highlights: [
      '3D Facade Rendering',
      'Modern & Contemporary Styles',
      'High-Resolution Facade Visualization',
      'Lighting & Material Previews',
    ],
    heroImage: '/images/3d/1.png',
    gallery: [
      '/images/3d/1.png',
      '/images/3d/2.png',
      '/images/3d/3.png',
      '/images/3d/4.jpeg',
      '/images/3d/5.jpeg',
      '/images/3d/6.png',
      '/images/3d/7.png',
      '/images/3d/8.png',
      '/images/3d/9.png',
      '/images/3d/10.png',
      '/images/3d/11.png',
      '/images/3d/12.png',
      '/images/3d/13.png',
      '/images/3d/14.png',
      '/images/3d/15.png',
      '/images/3d/18.png',
      '/images/3d/19.png',
      '/images/3d/20.png',
      '/images/3d/21.png',
      '/images/3d/22.png',
      '/images/3d/24.png',
    ],
  },
}